'''
Self explanitory
'''
import pygame
CLOCK = pygame.time.Clock()
FPS_CAP = CLOCK.tick(60)

PLAYER_SPEED = 0.3
HITBOX_OFFSET = 13
PLAYER_HITBAR_SPEED = 1

SWORD_OFFSET_X = 19.5
SWORD_OFFSET_Y = 19
SWORD_HB_OFFSET = -20

MELEE_E_SPEED = 0.15